allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext.flutter = [
    compileSdkVersion: 34,
    minSdkVersion    : 23,
    targetSdkVersion : 34
]

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    ext.flutter = rootProject.ext.flutter
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects { subproject ->
    if (subproject.name != 'app') {
        if (subproject.state.executed) {
            if (subproject.hasProperty('android')) {
                subproject.android {
                    if (namespace == null) {
                        namespace subproject.group
                    }
                    compileSdkVersion 34
                    buildToolsVersion "34.0.0"
                }
            }
        } else {
            subproject.afterEvaluate { p ->
                if (p.hasProperty('android')) {
                    p.android {
                        if (namespace == null) {
                            namespace p.group
                        }
                        compileSdkVersion 34
                        buildToolsVersion "34.0.0"
                    }
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


